[package]
name = "animagram/state-engine"
version = "0.2.0"
description = "Declarative state data management system for process"
license = "MIT"

[[module]]
name = "state-engine"
source = "target/wasm32-wasi/release/state-engine.wasm"
abi = "wasi"

[[command]]
name = "state-engine"
module = "state-engine"